package com.feldman.scholix.ui

import android.annotation.SuppressLint
import android.util.Log
import android.webkit.CookieManager
import android.webkit.WebStorage
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.compose.foundation.layout.size
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.alpha
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.compose.ui.viewinterop.AndroidView
import androidx.core.net.toUri
import com.feldman.scholix.api.platforms.StudentsPortalPlatform
import kotlinx.coroutines.delay
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlinx.coroutines.withTimeoutOrNull
import org.json.JSONObject
import java.util.concurrent.atomic.AtomicBoolean
import kotlin.coroutines.resume

/**
 * Invisible Ministry-of-Education sign-in for the Students & Graduates Portal.
 *
 * The user types their credentials into Scholix's own fields; this drives the MOE
 * login page off-screen (1dp, fully transparent) and returns the session cookie
 * plus the `csrt` token. No browser UI is ever shown.
 *
 * Why an engine is needed for THIS ONE STEP: lgn.edu.gov.il sits behind F5
 * Distributed Cloud Bot Defense (`server: volt-adc`). Its login requires an
 * `x-security-csrf-token` header generated by obfuscated /TSbd/ JavaScript that
 * fingerprints the browser. A plain HTTP client gets the password *validated*
 * (a wrong password still returns `isError:true`) but is never granted a session
 * -- proven across 16 completion variants and 4 header variants. The DATA
 * endpoints have no such check, so everything after login is plain OkHttp.
 *
 * This mirrors moe_portal.py's `StudentsPortal.login()`, which is confirmed
 * working end to end (3/3 fresh logins returning real grades).
 *
 * Two details that matter:
 *  * F5 serves auto-submitting interstitials on lgn.edu.gov.il BEFORE the real
 *    login page, so the form fill is retried across navigations rather than
 *    fired once on the first lgn page.
 *  * `csrt` is injected by site JS (it is in no HTML/header/cookie) and the
 *    portal API 404s without it, so it is read from the live DOM.
 *
 * @param onResult (cookies, csrt, error) — exactly one of cookies/error is non-null.
 */
@SuppressLint("SetJavaScriptEnabled")
@Composable
fun HiddenMoeLogin(
    username: String,
    password: String,
    timeoutMs: Long = 90_000,
    onResult: (cookies: String?, csrt: String?, error: String?) -> Unit,
) {
    val context = LocalContext.current
    val done = remember { AtomicBoolean(false) }
    val filled = remember { AtomicBoolean(false) }

    fun finish(cookies: String?, csrt: String?, error: String?) {
        if (done.compareAndSet(false, true)) onResult(cookies, csrt, error)
    }

    val web = remember {
        val cm = CookieManager.getInstance()
        cm.setAcceptCookie(true)
        // Start from a clean slate. A stale education.gov.il cookie makes
        // EduLogin bounce straight back to the portal ANONYMOUSLY, which used to
        // look like instant success (the portal sets a Dynatrace cookie even for
        // anonymous visitors) and produced no csrt and TZehut=-1.
        cm.removeAllCookies(null)
        cm.flush()
        WebStorage.getInstance().deleteAllData()

        WebView(context).apply {
            cm.setAcceptThirdPartyCookies(this, true)
            settings.javaScriptEnabled = true
            settings.domStorageEnabled = true

            webViewClient = object : WebViewClient() {
                override fun onPageFinished(view: WebView?, url: String?) {
                    super.onPageFinished(view, url)
                    if (done.get()) return
                    val host = runCatching { url?.toUri()?.host }.getOrNull().orEmpty()
                    Log.d(TAG, "page: $host (submitted=${filled.get()})")
                }
            }
            loadUrl(StudentsPortalPlatform.EDULOGIN_URL)
        }
    }

    // Drive the flow from Kotlin: F5 serves auto-submitting interstitials on
    // lgn.edu.gov.il before the real form, and Angular renders it async, so both
    // "fill the form" and "we're done" are polled rather than fired once.
    LaunchedEffect(username, password) {
        val completed = withTimeoutOrNull(timeoutMs) {
            while (!done.get()) {
                val host = runCatching { web.url?.toUri()?.host }.getOrNull().orEmpty()

                if (!filled.get() && host.endsWith("lgn.edu.gov.il", true)) {
                    web.evaluateJavascript(loginJs(username, password)) { r ->
                        when (val res = r?.trim('"', ' ')) {
                            "filled" -> {
                                Log.d(TAG, "credentials submitted")
                                filled.set(true)
                            }
                            null, "", "null", "noform" -> Unit  // not rendered yet
                            else -> if (res.startsWith("error")) finish(null, null, res)
                        }
                    }
                }

                // Only treat the portal as success once we actually signed in --
                // an anonymous visit also lands here and sets cookies.
                if (filled.get() && host.equals("students.education.gov.il", true)) {
                    val csrt = suspendEvaluate(web, CSRT_JS)
                        ?.trim('"', ' ')?.takeIf { it.isNotBlank() && it != "null" }
                    if (csrt != null) {
                        val cookie = CookieManager.getInstance()
                            .getCookie(StudentsPortalPlatform.BASE)
                        if (!cookie.isNullOrBlank()) {
                            Log.d(TAG, "signed in; csrt=$csrt")
                            finish(cookie, csrt, null)
                            return@withTimeoutOrNull true
                        }
                    }
                    // csrt is injected by the SPA's own JS shortly after load.
                }
                delay(500)
            }
            true
        }
        if (completed == null) {
            finish(null, null,
                if (filled.get())
                    "Signed in, but the Ministry of Education portal did not " +
                        "finish loading. Please try again."
                else
                    "Ministry of Education login timed out. Check your username " +
                        "and password and try again.")
        }
    }

    AndroidView(
        modifier = Modifier.size(1.dp).alpha(0f),
        factory = { web },
    )
}

private const val TAG = "HiddenMoeLogin"

/**
 * evaluateJavascript as a suspend call, so the poll loop can read its result.
 *
 * The timeout matters: WebView drops pending callbacks when the page navigates
 * underneath them, which this SSO chain does constantly, and one lost callback
 * would otherwise wedge the poll loop for the whole login. A lost answer just
 * means retry on the next tick.
 */
private suspend fun suspendEvaluate(
    web: WebView,
    js: String,
    timeoutMs: Long = 3_000,
): String? = withTimeoutOrNull(timeoutMs) {
    suspendCancellableCoroutine { cont ->
        try {
            web.evaluateJavascript(js) { value ->
                if (cont.isActive) cont.resume(value)
            }
        } catch (e: Exception) {
            if (cont.isActive) cont.resume(null)
        }
    }
}

private const val CSRT_JS =
    "(function(){var m=(document.documentElement.innerHTML||'').match(/csrt=(\\d{6,})/);" +
        "if(!m){m=(location.href||'').match(/csrt=(\\d{6,})/);}return m?m[1]:'';})()"

/**
 * Fill the Angular login form and submit it. Values are set through the native
 * value setter plus an `input` event so Angular's form model updates (assigning
 * `.value` alone leaves the model empty). Returns "filled", "noform", or
 * "error: ...". Running inside the page means the site's own JS applies --
 * including the bot-defense hook that adds `x-security-csrf-token`.
 */
private fun loginJs(username: String, password: String): String {
    val u = JSONObject.quote(username)
    val p = JSONObject.quote(password)
    return """
    (function(){
      try{
        function setVal(el, val){
          var d = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value');
          if (d && d.set) { d.set.call(el, val); } else { el.value = val; }
          el.dispatchEvent(new Event('input',  {bubbles:true}));
          el.dispatchEvent(new Event('change', {bubbles:true}));
          el.dispatchEvent(new Event('blur',   {bubbles:true}));
        }
        function pick(sels){
          for (var i=0;i<sels.length;i++){
            var el = document.querySelector(sels[i]);
            if (el) return el;
          }
          return null;
        }
        var user = pick(['input[formcontrolname="userName"]','input[name="userName"]',
                         'input[type="text"]:not([type="hidden"])']);
        var pass = pick(['input[formcontrolname="password"]','input[type="password"]']);
        if (!user || !pass) { return 'noform'; }
        setVal(user, $u);
        setVal(pass, $p);
        var btn = pick(['button[type="submit"]','form button','.login-button','button']);
        if (btn) { btn.click(); } else if (pass.form) { pass.form.submit(); }
        return 'filled';
      } catch(e){ return 'error: ' + e; }
    })()
    """.trimIndent()
}
